name: apk_builder
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
          weight: 400
        - asset: fonts/Schyler-Italic.ttf
          style: italic
          weight: 400
    - family: Trajan Pro
      fonts:
        - asset: fonts/TrajanPro-Regular.ttf
