
name: Build and Release Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Use Java 17, recommended for modern Android builds
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Create project structure if it doesn't exist. This makes the workflow robust.
      - name: Create Flutter Project
        run: flutter create .

      - name: Get dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "Decoding keystore..."
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
        
      - name: Create key.properties
        run: |
          echo "Creating key.properties..."
          echo "storePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> android/key.properties
          # The path to the keystore file relative to the 'android' directory
          echo "storeFile=../app/upload-keystore.jks" >> android/key.properties

      - name: Build APK
        run: |
          # Clean previous builds to be safe
          flutter clean
          flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
