name: Build Flutter APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
      - name: Decode Keystore
        id: decode_keystore
        run: | 
          echo "::set-output name=keystore_file_path::$(mktemp)"
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > ${{ steps.decode_keystore.outputs.keystore_file_path }}
      - name: Build APK
        run: | 
          keytool -importkeystore -srckeystore ${{ steps.decode_keystore.outputs.keystore_file_path }} -destkeystore android/app/my-release-key.keystore -deststoretype JKS
          flutter build apk --release --build-name=1.0.0 --build-number=1 --keystore-properties-file=android/app/my-release-key.keystore
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk