name: Build Flutter APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: ''
      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Configure Android SDK
        run: echo "sdk.dir=${{ env.ANDROID_SDK_ROOT }}" > android/local.properties
      - name: Decode Keystore
        id: decode-keystore
        run: | 
          KEYSTORE_BASE64="${{ secrets.RELEASE_KEYSTORE_BASE64 }}"
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/release-keystore.jks
          chmod 600 android/app/release-keystore.jks
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk