name: Build and Release Flutter APK

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'false'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Create Flutter Project
        run: flutter create .
        if: success()
      - name: Override main.dart
        run: | 
          echo "import 'package:flutter/material.dart';\n\nvoid main() {\n  runApp(MyApp());\n}\n\nclass MyApp extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      home: Scaffold(\n        appBar: AppBar(title: Text('APK Built by Gemini!')),\n        body: Center(child: Text('APK Built by Gemini!')),\n      ),\n    );\n  }\n}" > lib/main.dart
        if: success()
      - name: Get dependencies
        run: flutter pub get
        if: success()
      - name: Decode Keystore
        run: | 
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore
        if: success()
      - name: Create key.properties
        run: | 
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=android/app/my-release-key.keystore" >> android/key.properties
        if: success()
      - name: Build APK
        run: flutter build apk --release
        if: success()
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
        if: success()      
      - name: Print Success Message
        run: echo "APK built and uploaded successfully!"
        if: success()
      - name: Fail on any previous step failure
        if: failure()
        run: exit 1