name: Build Flutter APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Decode Keystore
        id: decode_keystore
        run: | 
          echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.keystore
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
      - name: Build APK
        run: flutter build apk --release --build-name=1.0.0 --build-number=1
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/*.apk
