# .github/workflows/generate_code.yml

name: Generate Code with Gemini

on:
  # Cho phép kích hoạt từ xa qua API
  repository_dispatch:
    types: [generate-code] # Đặt một tên sự kiện tùy ý, ví dụ 'generate-code'
  
  # Giữ lại workflow_dispatch để có thể chạy thủ công trên web nếu muốn
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai requests

      # Script này bây giờ nằm trong repo và được Action chạy
      - name: Run Gemini Code Generator
        run: python generate_and_commit.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Dùng GITHUB_TOKEN có sẵn của Action, nhớ cấp quyền ghi cho nó
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
